steps:
  # Install Python dependencies
  - name: 'python:3.11'
    entrypoint: 'pip'
    args:
      - 'install'
      - '--user'
      - 'huggingface_hub'
      - 'google-cloud-storage'
    id: 'install-deps'

  # Download models and upload to GCS
  - name: 'python:3.11'
    entrypoint: 'python'
    args:
      - 'download_models.py'
    id: 'download-models'
    waitFor: ['install-deps']

timeout: 7200s  # 2 hour timeout (SDXL + other models are large)

options:
  machineType: 'E2_HIGHCPU_32'  # GPU best practice: use powerful build machine
  diskSizeGb: 500  # GPU best practice: large disk for SDXL models
  logging: CLOUD_LOGGING_ONLY
