steps:
  # 1. Build the base image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/jhakaas-repo/worker-base:latest',
      '.'
    ]

  # 2. Push the base image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/jhakaas-repo/worker-base:latest'
    ]

# Substitutions
substitutions:
  _REGION: asia-southeast1

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
