steps:
  # 1. Build the base image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/jhakaas-repo/worker-base:latest',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/jhakaas-repo/worker-base:${SHORT_SHA}',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/jhakaas-repo/worker-base:v1.0.0',
      '.'
    ]
    timeout: 1200s  # 20 minutes - first build is slow

  # 2. Push the base image with latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/jhakaas-repo/worker-base:latest'
    ]

  # 3. Push the base image with commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/jhakaas-repo/worker-base:${SHORT_SHA}'
    ]

  # 4. Push the base image with version tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/jhakaas-repo/worker-base:v1.0.0'
    ]

# Substitutions allow us to pass variables at build time
substitutions:
  _REGION: asia-southeast1

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Use a bigger machine for faster builds
  timeout: 1800s  # 30 minutes total timeout
